services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      MESSAGE: "Hello world from Docker Compose!"
      FLASK_RUN_PORT: 8080
      JAEGER_AGENT_HOST: jaeger
  
  prometheus:
    image: prom/prometheus:v2.53.2
    volumes:
      - ./prometheus:/etc/prometheus/
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
  
  jaeger:
    image: jaegertracing/all-in-one:1.46
    ports:
      - "5755:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"

networks:
  default:
    name: flask-app-network
    driver: bridge